### PR TITLE
Countdown interpolation

### PR DESCRIPTION
**Pull request by noscript**
Adds option to display countdown in status line.

### CODE REVIEW

**Comment by bruno-** [comment]
Hmm.. I'm now sure why would this feature be useful?

**Comment by noscript** [comment]
That allowed me to estimate how long ago the session was saved (by subtracting countdown from save interval). It was more a fun experiment to study the source code. I think this PR isn't very useful to anyone, I better just I close it :)

**Comment by szymonmaszke** [comment]
I would be interested in this feature as well. @bruno- @noscript maybe you could reconsider your position?

**Comment by noscript** [comment]
Of course I can re-submit the PR if @bruno- considers it.

**Comment by PetarMetodiev** [comment]
This seems like a nice option to have. To me it seems more useful than `#{continuum_status}`

**Pull request closed without merging**
