### PR TITLE
Add option to allow kill the default sessions created when tmux server starts

### PR DESCRIPTION
**Pull request by paulhybryant**
Add option to allow kill the default sessions created when tmux server starts.

### CODE REVIEW

**Comment by sappo** [comment]
This is exactly the feature I'm looking for. Please do merge!
Unless there is an easier way to kill that tedious default session.

**Comment by sappo** [comment]
@bruno- this PR solve a valid problem? At least to me and a few of my colleagues. What's the reason for not merging it? If there's a valid reason let's fix it!

**Comment by mnarrell** [comment]
Can we have this merged please?

**Comment by jasperzs** [comment]
@bruno-  Can we please merge this PR?

**Comment by bruno-** [comment]
Hi, sorry for the long wait on this one.

Why not make this an option in `tmux-resurrect`? I can see users using only `tmux-resurrect` without `tmux-continuum` wanting the same feature.
And really, only `tmux-resurrect` should be concerned about the restored content of the tmux env.

**Comment by martinisoft** [comment]
I do this as a resurrect hook in my tmux conf `set -g @resurrect-hook-post-restore-all 'tmux kill-session -t 0'` and it works like a charm, no hacks needed.

**Comment by aguytech** [comment]
> I do this as a resurrect hook in my tmux conf `set -g @resurrect-hook-post-restore-all 'tmux kill-session -t 0'` and it works like a charm, no hacks needed.
I'm sorry but when you use the script tmux-resurrect/scripts/restore.sh to restore session, the plugin insert saved sessions with numeric id in the first ids.
So if you kept one session with an id equal to "0", the id of saved session is retored and the new session id is modify to 1.
So if you kill automaticaly the session "0", you kill saved session.
Your solution works if you don't save session with id "0".

Your solution is not satisfactory for an uninformed user

**Comment by aguytech** [comment]
> I do this as a resurrect hook in my tmux conf `set -g @resurrect-hook-post-restore-all 'tmux kill-session -t 0'` and it works like a charm, no hacks needed.

I'm sorry but when you use the script tmux-resurrect/scripts/restore.sh to restore session, the plugin insert saved sessions with numeric id in the first ids.
So if you kept one session with an id equal to "0", the id of saved session is retored and the new session id is modify to 1.
So if you kill automaticaly the session "0", you kill saved session.

Your solution works if you don't save session with id "0".

**Comment by bruno-** [comment]
This feature is implemented in tmux-resurrect

https://github.com/tmux-plugins/tmux-resurrect/commit/5f5f9d8fd5ff9769e5ef08d64a430ee7ab525dc7

**Comment by aguytech** [comment]
Ok I tried 10mn ago with a fresh install of tmux-resurrect & tmux-continuum from github. my tmux version are 3.1_c-1

Everything works like a charm except this :

Just try to repeat 3 times this command :
`systemctl restart --user tmux.service`

and tell me whats happen with your list of sessions ?
Here is for me :
```
$ tmux ls
0: 1 windows (created Sun Nov 29 01:04:07 2020)
$ systemctl restart --user tmux.service
$ systemctl restart --user tmux.service
$ systemctl restart --user tmux.service
$ tmux ls
0: 1 windows (created Sun Nov 29 01:14:50 2020)
1: 1 windows (created Sun Nov 29 01:14:50 2020)
2: 1 windows (created Sun Nov 29 01:14:50 2020)
3: 1 windows (created Sun Nov 29 01:14:51 2020)
```
Something seems to be wrong?

Here is my file .tmux.conf without binds:

```
# prefix key
set-option -g prefix C-q
# time allowed to repeat key following prefix key
set-option -g repeat-time 500
# set history to 5000
set-option -g history-limit 5000

# tmux-continuum
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'

####  plugins

# resurect plugin
run-shell ~/.tmux/plugins/tmux-resurrect/resurrect.tmux
run-shell ~/.tmux/plugins/tmux-continuum/continuum.tmux
```

**Pull request closed without merging**
